name: Flatter

on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  build:
    name: Build with Flatter

    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build with Flatter
        uses: andyholmes/flatter@main
        with:
          files: |
            com.jetbrains.PhpStorm.json
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: true
          flatpak-builder-args: |
            --install-deps-from=flathub

  deploy:
    name: Deploy to GitHub Pages

    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
